-- MySQL Script generated by MySQL Workbench
-- Mon May 15 17:47:31 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema friendships
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema friendships
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `friendships` DEFAULT CHARACTER SET utf8 ;
USE `friendships` ;

-- -----------------------------------------------------
-- Table `friendships`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `friendships`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `friendships`.`friendships`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `friendships`.`friendships` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `user_id` INT NOT NULL,
  `friend_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_friendships_users_idx` (`user_id` ASC),
  INDEX `fk_friendships_users1_idx` (`friend_id` ASC),
  CONSTRAINT `fk_friendships_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `friendships`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_friendships_users1`
    FOREIGN KEY (`friend_id`)
    REFERENCES `friendships`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data
-- -----------------------------------------------------

LOCK TABLES users WRITE;
/*!40000 ALTER TABLE `users` DISABLE KEYS */;
INSERT INTO users VALUES
(1,'Chris','Baker','2017-05-15 17:00:01','2017-05-15 17:00:01'),
(2,'Jessica','Davidson','2017-05-15 17:00:02','2017-05-15 17:00:02'),
(3,'James','Johnson','2017-05-15 17:00:03','2017-05-15 17:00:03'),
(4,'Diana','Smith','2017-05-15 17:00:04','2017-05-15 17:00:04')
;
/*!40000 ALTER TABLE `users` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES friendships WRITE;
/*!40000 ALTER TABLE `friendships` DISABLE KEYS */;
INSERT INTO friendships VALUES
(1,'2017-05-15 17:00:05','2017-05-15 17:00:05',1,2),
(2,'2017-05-15 17:00:06','2017-05-15 17:00:06',1,3),
(3,'2017-05-15 17:00:07','2017-05-15 17:00:07',1,4),
(4,'2017-05-15 17:00:08','2017-05-15 17:00:08',2,1),
(5,'2017-05-15 17:00:09','2017-05-15 17:00:09',3,1),
(6,'2017-05-15 17:00:10','2017-05-15 17:00:10',4,1)
;
/*!40000 ALTER TABLE `friendships` ENABLE KEYS */;
UNLOCK TABLES;
