# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-22 21:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_wall', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comments',
            new_name='comment',
        ),
    ]
