# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-22 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anthologies', '0002_auto_20170522_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books_has_authors',
            name='author_id',
        ),
        migrations.RemoveField(
            model_name='books_has_authors',
            name='book_id',
        ),
        migrations.AddField(
            model_name='books',
            name='authors',
            field=models.ManyToManyField(to='anthologies.Authors'),
        ),
        migrations.DeleteModel(
            name='Books_has_Authors',
        ),
    ]
