# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-22 19:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books_and_authors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books_and_authors.Authors'),
        ),
    ]
